version: "3"
services:
  siap-db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=siap
      - POSTGRES_PASSWORD=siap
      - POSTGRES_MULTIPLE_DATABASES=siap-test
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 6543:5432
  siap:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "9000:8000"
    depends_on:
      - siap-db

volumes:
  data:
    driver: local
  pgdata:
