# Generated by Django 3.2.10 on 2021-12-28 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('ville_signature', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bailleur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nom', models.CharField(max_length=255)),
                ('siret', models.CharField(max_length=14)),
                ('capital_social', models.FloatField(null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('code_postal', models.CharField(max_length=255, null=True)),
                ('ville', models.CharField(max_length=255, null=True)),
                ('signataire_nom', models.CharField(max_length=255, null=True)),
                ('signataire_fonction', models.CharField(max_length=255, null=True)),
                ('signataire_date_deliberation', models.DateField(null=True)),
                ('operation_exceptionnelle', models.TextField(null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nom', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10, null=True)),
                ('ville', models.CharField(max_length=255, null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('numero_galion', models.CharField(max_length=255, null=True)),
                ('annee_gestion_programmation', models.IntegerField(null=True)),
                ('zone_123', models.IntegerField(null=True)),
                ('zone_abc', models.CharField(max_length=255, null=True)),
                ('surface_utile_totale', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('type_habitat', models.CharField(choices=[('SANSOBJET', 'Sans Objet'), ('INDIVIDUEL', 'Individuel'), ('COLLECTIF', 'Collectif')], default='INDIVIDUEL', max_length=25)),
                ('type_operation', models.CharField(choices=[('SANSOBJET', 'Sans Objet'), ('NEUF', 'Construction Neuve'), ('ACQUIS', 'Acquisition-Amélioration'), ('DEMEMBREMENT', 'Démembrement'), ('REHABILITATION', 'Réhabilitation'), ('SANSTRAVAUX', 'Sans travaux'), ('USUFRUIT', 'Usufruit'), ('VEFA', 'VEFA')], default='NEUF', max_length=25)),
                ('anru', models.BooleanField(default=False)),
                ('nb_locaux_commerciaux', models.IntegerField(null=True)),
                ('nb_bureaux', models.IntegerField(null=True)),
                ('autres_locaux_hors_convention', models.TextField(null=True)),
                ('date_achevement_previsible', models.DateField(null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('administration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.administration')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.bailleur')),
            ],
        ),
    ]
