# Generated by Django 3.2.10 on 2022-01-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='autre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='plai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='pls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='plus',
            field=models.BooleanField(default=False),
        ),
    ]
