# Generated by Django 3.2.10 on 2022-01-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20220103_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='apilos_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='bailleur',
            name='apilos_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
