# Generated by Django 3.2.10 on 2022-01-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20220105_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='apilos_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
