# Generated by Django 3.2.10 on 2022-01-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_operation_apilos_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='autre',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='plai',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='pls',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='plus',
        ),
        migrations.AddField(
            model_name='operation',
            name='nb_autre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='nb_plai',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='nb_pls',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='nb_plus',
            field=models.IntegerField(null=True),
        ),
    ]
